#!/usr/bin/perl

# Use external modules
use strict;
use Config;
use threads;
use threads::shared;
use Thread::Queue;
use Data::Dumper;
use POSIX;
use Proc::Daemon;
use Time::HiRes;

# Check perl for threads support
$Config{useithreads} or die "Recompile Perl with threads to run this program.";

# Include parts of system
require '/opt/mmm/lib/config.pm';
require '/opt/mmm/lib/log.pm';

#-----------------------------------------------------------------
# Read config file
my $cfg_file = "/opt/mmm/mmm_angel.conf";
print "Config file: $cfg_file\n";
our $config = ReadConfig($cfg_file);
my $shutdown = 0;

# Go to background
Proc::Daemon::Init if ($config->{debug} =~ /^(off|no|0)$/i);
CreatePidFile();

# Catch signals
$SIG{INT} = \&SignalHandler;
$SIG{TERM} = \&SignalHandler;

# Call main function
DaemonMain();

exit(0);

#-----------------------------------------------------------------
sub DaemonMain() {
    while (!$shutdown) {
        foreach my $service (keys(%{$config->{service}})) {
	    my $s = $config->{service}->{$service};
	    next if ($s->{disabled});
	    
	    CheckService($s);
	}

	# sleep before next check
	sleep($config->{check_period});
    }
}

#-----------------------------------------------------------------
sub CheckService($) {
    my $service = shift;
    
    LogDebug("Checking service: $service->{description}");
    
    my $pid = $service->{pid};
    my $cmd = $service->{command};
    
    if (CheckPid($pid)) {
        LogDebug("Service '$service->{description}' is OK");
	return 1;
    }
    
    LogTrap("Warning: Service '$service->{description}' is dead! Restarting it...");
    my $res = system("nohup $cmd &> /dev/null &");
    if ($res) {
        LogError("Error: Can't execute command: '$cmd'");
	SendEmailNotice("'$service->{description}' is dead! Restart try failed!");
	return 1;
    }
    LogTrap("Notice: Service '$service->{description}' has been restarted successfully");
    SendEmailNotice("'$service->{description}' is dead! Restarted successfully!");
    sleep(5);
}

#-----------------------------------------------------------------
sub CheckPid($) {
    my $pid_file = shift;

    open(PID, $pid_file) || return 0;
    chomp(my $pid = <PID>);
    close(PID);
    
    return 0 unless ($pid);
    return 0 unless (kill(0, $pid));

    return 1;
}

#-----------------------------------------------------------------
sub SignalHandler() {
    LogDebug("Core: Signal received: exiting...");
    $shutdown = 1;
}

#-----------------------------------------------------------------
sub SendEmailNotice($) {
    my $msg = shift;
    my $now = strftime("%Y-%m-%d %H:%M:%S", localtime);
    
    my $sendmail = "/usr/sbin/sendmail -t";
    my $res = open(SENDMAIL, "|$sendmail");
    unless ($res) { 
        LogError("Error: Cannot open $sendmail: $!");
	return 1;
    }
    print SENDMAIL "From: mmm_mon\@sphere.com\n";
    print SENDMAIL "Subject: [$now] MMM Service failure\n";
    print SENDMAIL "To: $config->{admin_email}\n\n";
    print SENDMAIL "$now: $msg\n";
    close(SENDMAIL);
}
